# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=128)),
                ('post_type', models.CharField(default='', max_length=128)),
                ('post_views', models.IntegerField(default=0)),
                ('post_endorsements', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=128, unique=True)),
                ('game_type', models.CharField(max_length=128)),
                ('game_genre', models.CharField(max_length=128)),
                ('player_number', models.IntegerField(default=0)),
                ('game_views', models.IntegerField(default=0)),
                ('game_endoresments', models.IntegerField(default=0)),
                ('game_image', models.ImageField(blank=True, upload_to='game_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=128, unique=True)),
                ('user_views', models.IntegerField(default=0)),
                ('user_endorsements', models.IntegerField(default=0)),
                ('user_image', models.ImageField(blank=True, upload_to='user_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dice.Category')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dice.User'),
        ),
    ]
