# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start', models.DateTimeField(null=True)),
                ('event_end', models.DateTimeField(null=True)),
                ('event_location', models.CharField(max_length=200, null=True)),
                ('game', models.CharField(max_length=200)),
                ('description', models.TextField(default='Please add a description:')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='user_image')),
                ('bio', models.CharField(max_length=800)),
                ('player_endorsements', models.IntegerField(default=0)),
                ('player_location', models.CharField(max_length=200, null=True)),
                ('games_list', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='post_user',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_endoresments',
            new_name='dislikes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_site',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dice.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees', to='dice.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dice.User'),
        ),
    ]
