# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
