# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='player_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
