# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_auto_20190312_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_endoresments',
            new_name='game_endorsements',
        ),
    ]
