# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_auto_20190321_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='user_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_endorsements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='player_endorsements',
        ),
    ]
