# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_auto_20190311_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, upload_to='game_image'),
        ),
    ]
