# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0004_auto_20190313_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('game', models.CharField(max_length=200)),
                ('description', models.TextField(default='Please add a description')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=128)),
                ('post_type', models.CharField(default='', max_length=128)),
                ('post_views', models.IntegerField(default=0)),
                ('post_endorsements', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='forum',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dice.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees', to='dice.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dice.User'),
        ),
    ]
