# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0006_auto_20190314_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='post_user',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
