# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0007_auto_20190314_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_site',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
