# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0008_game_game_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='user_image')),
                ('bio', models.CharField(max_length=800)),
                ('player_endorsements', models.IntegerField(default=0)),
                ('player_location', models.CharField(max_length=200, null=True)),
                ('games_list', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dice.User')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='event_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='event_location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='event_start',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Please add a description:'),
        ),
    ]
