# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0009_auto_20190318_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_name',
        ),
    ]
